stages:          
  - build

build_ubuntu:       
  image: ubuntu:20.04
  stage: build
  timeout: 30 minutes
  tags:
    - gfw_free
  artifacts:
    paths:
      - build
  script:
    - echo $SHELL
    - lscpu
    - bash ci/pkg_install.sh
    - make dep_build
    - make configure
    - make build
    - make run
    - make bench