stages:          
  - build

build_debian:       
  image: rust:1.58.0
  stage: build
  timeout: 30 minutes
  tags:
    - gfw_free
  artifacts:
    paths:
      - build
  script:
    - echo $SHELL
    - lscpu && free -h && df -h
    - cat /etc/*release
    - bash ci/prepare_deb.sh
    - make configure
    - make build
    - make run
    - rustc --version
    - cd et_rust && cargo bench | grep time
    - rustup install nightly
    - cargo +nightly bench | grep time
