name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    container: debian:11
    steps:
      - uses: actions/checkout@v2

      - name: Distro setup
        run: |
          bash ci/deb_install.sh
          bash ci/download_dep.sh
          bash ci/setup_cmake_projects.sh

      - name: Compile and Run
        shell: bash
        run: |
          source $HOME/.cargo/env
          make configure
          make build
          make run
          make bench
