name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build docker 
        run: |
          make docker_build
          chmod +x ci/run_in_docker.sh

      - name: Build dep
        run: |
          ci/run_in_docker.sh make dep_download
          ci/run_in_docker.sh make dep_build

      - name: Build
        shell: bash
        run: |
          ci/run_in_docker.sh make configure
          ci/run_in_docker.sh make build

      - name: Run and bench
        shell: bash
        run: |
          ci/run_in_docker.sh make run
          ci/run_in_docker.sh make bench
