name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build_container:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Test container building
        run: |
          bash ci/docker_build.sh

  run:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build docker 
        run: |
          bash ci/pkg_install.sh

      - name: Build dep
        run: |
          make dep_build

      - name: Build
        shell: bash
        run: |
          make configure
          make build

      - name: Run and bench
        shell: bash
        run: |
          make run
          make bench
