name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    container: debian:11
    steps:
      - uses: actions/checkout@v2

      - name: Distro setup
        run: |
          bash ci/pkg_install.sh

      - name: Build dep
        run: |
          bash ci/dep_download.sh
          bash ci/dep_build.sh

      - name: Build
        shell: bash
        run: |
          make configure
          make build

      - name: Run and bench
        shell: bash
        run: |
          make run
          make bench
