name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    container: debian:sid

    steps:
      - uses: actions/checkout@v2

      - name: Distro setup
        run: |
          bash ci/deb_install.sh
          bash ci/vcpkg_setup.sh

      - name: Compile and Run
        run: |
          PATH="$HOME/.cargo/bin:$PATH"
          make configure
          make build
          make run
          make bench
