name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build_container:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check builder
        run: |
          lscpu
          free -h 
          df -h

      - name: Test container building
        run: |
          bash ci/docker_build.sh

  run:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check builder
        run: |
          lscpu
          free -h 
          df -h

      - name: Build docker 
        run: |
          bash ci/build_in_docker.sh
