name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check builder
        run: |
          lscpu
          free -h 
          df -h

      - name: Docker build
        run: |
          bash ci/docker_build.sh

      - name: Dep build
        run: |
          bash ci/docker_run_0_dep_build.sh

      - name: Build
        run: |
          bash ci/docker_run_1_build.sh

      - name: Run
        run: |
          bash ci/docker_run_2_run.sh
        
      

